### ISSUE TITLE
Toggling comments

### ISSUE THREAD

**Issue by mortensorensen** [quintanar401/language-kdb-q#1]
May not be an issue with the package, but what is the best approach to get toggle comment functionality? By default, pressing Cmd-/ gives
```
/*
some code
some more code*/
```
Would be great if the correct functionality could be added to the package without setting up new key bindings or installing other packages.

Thanks

**Comment by quintanar401** [comment]
What do you think the correct functionality should be? I guess this binding is from some other package.

**Comment by mortensorensen** [comment]
It would be to have each selected line prefixed by `/ ` when pressing Cmd-/. In Sublime this is achieved by adding a `Comments.tmPreferences` file (see https://github.com/komsit37/sublime-q/blob/master/syntax/Comments.tmPreferences). I am unsure how (and if) this is possible in Atom, hence the question. But I doubt people comment out blocks of code manually, so would like to get some pointers on this.

**Comment by quintanar401** [comment]
I've added this to settings but I used // for comments because / may accidentally comment a blank line and this looks like EOF comment. If you prefer / add to your settings file this:
```
'.source.q':
  'editor':
    'commentStart': '/ '
```

**Comment by mortensorensen** [comment]
Works perfect. Thank you!
